server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/flypaopao/tensquare54.git
  rabbitmq:
    host: 192.168.73.140
management:  #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
